// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNQ8_3qBWZjDp2jAhYjyAGXKcgHNNAwhM',
    appId: '1:1059331365969:web:16b3b9627439ac935a6c70',
    messagingSenderId: '1059331365969',
    projectId: 'fir-user-6b81e',
    authDomain: 'fir-user-6b81e.firebaseapp.com',
    storageBucket: 'fir-user-6b81e.firebasestorage.app',
    measurementId: 'G-JPX5E70CYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-lt0oZajXEB67YIzss9XlZsS3AdMV5ek',
    appId: '1:1059331365969:android:095659184674b0bb5a6c70',
    messagingSenderId: '1059331365969',
    projectId: 'fir-user-6b81e',
    storageBucket: 'fir-user-6b81e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZIQh5UsSeVPK8lZ6VOyrtyR0Jv2i3XUg',
    appId: '1:1059331365969:ios:7d5e2bead25792955a6c70',
    messagingSenderId: '1059331365969',
    projectId: 'fir-user-6b81e',
    storageBucket: 'fir-user-6b81e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseproject',
  );
}
